import type { Options as DocsOptions } from "@docusaurus/plugin-content-docs";
import type { Options as PresetOptions } from "@docusaurus/preset-classic";
import type { Config } from "@docusaurus/types";
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { createAssetsPlugin } from "./framework/config/assets-plugin.js";
import type { SidebarItem } from "./framework/config/schema.js";
import { convertSidebar } from "./framework/config/sidebar.js";
import { NAVBAR_ICON_ITEMS, SHARED_COLOR_MODE } from "./framework/shared-config.js";

import { themes as prismThemes } from "prism-react-renderer";

const SITE_URL = "https://docs.trickfirerobotics.com";
const CONTENT_DIR = path.join(process.cwd(), "content");
const DEV_FIXTURES_DIR = path.join(process.cwd(), "dev-fixtures");
const GENERAL_DIR = path.join(process.cwd(), "general");
const IS_DEV = process.env.NODE_ENV !== "production";

function getFirstDocId(sidebar: SidebarItem[]): string | undefined {
    for (const item of sidebar) {
        if ("items" in item) {
            const first = getFirstDocId(item.items);
            if (first) return first;
        } else if (item.slug) {
            return item.slug;
        }
    }
    return undefined;
}

function makeRedirectHtml(url: string): string {
    return (
        `<!doctype html><html lang="en"><head><meta charset="UTF-8">` +
        `<title>Redirecting…</title>` +
        `<meta http-equiv="refresh" content="0; url=${url}">` +
        `<script>window.location.replace(${JSON.stringify(url)})</script></head>` +
        `<body><p>Redirecting to <a href="${url}">${url}</a>…</p></body></html>\n`
    );
}

interface RepoMeta {
    id: string;
    name: string;
    description: string;
    basePath: string;
    idPrefix: string;
    sidebarPath?: string;
    firstDocId?: string;
}

function buildRepoMeta(repoDir: string, repo: string): RepoMeta {
    const docsSubdir = path.join(repoDir, "docs");
    const hasDocsSubdir = existsSync(docsSubdir) && statSync(docsSubdir).isDirectory();
    const idPrefix = hasDocsSubdir ? "docs/" : "";
    try {
        const cfgPath = path.join(repoDir, "docs.config.json");
        const cfg = JSON.parse(readFileSync(cfgPath, "utf-8")) as {
            name?: string;
            description?: string;
            sidebar?: SidebarItem[];
        };

        let sidebarPath: string | undefined;
        let firstDocId: string | undefined;
        if (cfg.sidebar) {
            const converted = convertSidebar(cfg.sidebar, idPrefix);
            const generatedPath = path.join(repoDir, "sidebars.generated.js");
            writeFileSync(
                generatedPath,
                `// @generated by trickfire-docs — do not edit\nexport default { sidebar: ${JSON.stringify(converted, null, 2)} };\n`
            );
            sidebarPath = generatedPath;
            const rawFirstDocId = getFirstDocId(cfg.sidebar);
            firstDocId = rawFirstDocId ? idPrefix + rawFirstDocId : undefined;
        }

        return {
            id: repo,
            name: cfg.name ?? repo,
            description: cfg.description ?? "",
            basePath: repoDir,
            idPrefix,
            sidebarPath,
            firstDocId,
        };
    } catch {
        return { id: repo, name: repo, description: "", basePath: repoDir, idPrefix };
    }
}

function getReposFromDir(baseDir: string): RepoMeta[] {
    if (!existsSync(baseDir)) return [];
    return readdirSync(baseDir, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name)
        .sort()
        .map((repo) => buildRepoMeta(path.join(baseDir, repo), repo));
}

export default async function createConfig(): Promise<Config> {
    const repoMeta: RepoMeta[] = [
        ...(existsSync(GENERAL_DIR) ? [buildRepoMeta(GENERAL_DIR, "general")] : []),
        ...getReposFromDir(CONTENT_DIR),
        ...(IS_DEV ? getReposFromDir(DEV_FIXTURES_DIR) : []),
    ];

    const frameworkDocsPlugin: NonNullable<Config["plugins"]>[number] = [
        "@docusaurus/plugin-content-docs",
        {
            id: "framework",
            path: "docs",
            routeBasePath: "trickfire-docs",
            sidebarPath: "./docs-sidebars.js",
        } satisfies DocsOptions,
    ];

    const docsPlugins: Config["plugins"] = repoMeta.map(({ id, basePath, sidebarPath }) => [
        "@docusaurus/plugin-content-docs",
        {
            id,
            path: basePath,
            routeBasePath: id,
            exclude: ["**/assets/**"],
            ...(sidebarPath && { sidebarPath }),
        } satisfies DocsOptions,
    ]);

    const projectAssetsPlugin = createAssetsPlugin(
        repoMeta.map(({ id, basePath }) => ({
            assetsDir: path.join(basePath, "assets"),
            publicPath: `/${id}/assets`,
            outSubPath: `${id}/assets`,
        }))
    );

    const subprojectRedirectsPlugin: NonNullable<Config["plugins"]>[number] = () => ({
        name: "trickfire-subproject-redirects",
        postBuild({ outDir }: { outDir: string }) {
            for (const { id, firstDocId } of repoMeta) {
                const indexPath = path.join(outDir, id, "index.html");
                if (existsSync(indexPath)) continue;

                let target = firstDocId;
                if (!target) {
                    const repoOutDir = path.join(outDir, id);
                    if (!existsSync(repoOutDir)) continue;
                    target = readdirSync(repoOutDir, { withFileTypes: true })
                        .filter((d) => d.isDirectory())
                        .map((d) => d.name)
                        .sort()[0];
                }
                if (!target) continue;

                writeFileSync(indexPath, makeRedirectHtml(`/${id}/${target}/`));
            }
        },
    });

    const generalMeta = repoMeta.find(({ id }) => id === "general");
    const otherRepoMeta = repoMeta.filter(({ id }) => id !== "general");

    const toDropdownItem = ({ id, name, firstDocId }: RepoMeta) => ({
        label: name,
        ...(firstDocId ? { to: `/${id}/${firstDocId}/` } : { href: `/${id}/` }),
    });
    const otherProjectDropdownItems = otherRepoMeta.map(toDropdownItem);

    return {
        title: "TrickFire Robotics Docs",
        tagline: "Documentation for TrickFire Robotics projects",
        favicon: "favicon.ico",
        url: SITE_URL,
        baseUrl: "/",
        trailingSlash: true,
        staticDirectories: ["public"],
        onBrokenLinks: "warn",
        onBrokenMarkdownLinks: "warn",
        customFields: {
            repoMeta: otherRepoMeta.map(({ id, name, description, firstDocId }) => ({
                id,
                name,
                description,
                firstDocId,
            })),
            generalMeta: generalMeta
                ? {
                      id: generalMeta.id,
                      name: generalMeta.name,
                      description: generalMeta.description,
                      firstDocId: generalMeta.firstDocId,
                  }
                : undefined,
            frameworkMeta: {
                name: "Docs Framework",
                description: "Documentation for the TrickFire Docs framework itself",
                routeBasePath: "trickfire-docs",
            },
        },
        future: {
            faster: {
                rspackBundler: true,
                rspackPersistentCache: true,
                swcJsLoader: true,
                swcJsMinimizer: true,
                swcHtmlMinimizer: true,
            },
        },
        themeConfig: {
            colorMode: SHARED_COLOR_MODE,
            navbar: {
                title: "",
                logo: {
                    alt: "TrickFire Robotics logo",
                    src: "nav-logo.png",
                    srcDark: "nav-logo.png",
                    width: 80,
                    height: 30,
                },
                items: [
                    ...(generalMeta
                        ? [{ ...toDropdownItem(generalMeta), position: "left" as const }]
                        : []),
                    {
                        to: "/trickfire-docs/",
                        label: "Docs Framework",
                        position: "left" as const,
                    },
                    ...otherProjectDropdownItems.map((item) => ({
                        ...item,
                        position: "left" as const,
                    })),
                    ...NAVBAR_ICON_ITEMS,
                ],
            },
            prism: {
                theme: prismThemes.nightOwl,
                darkTheme: prismThemes.nightOwl,
            },
        },
        presets: [
            [
                "classic",
                {
                    docs: false,
                    blog: false,
                    theme: { customCss: ["./src/css/custom.css"] },
                } satisfies PresetOptions,
            ],
        ],
        plugins: [
            frameworkDocsPlugin,
            ...docsPlugins,
            subprojectRedirectsPlugin,
            projectAssetsPlugin,
        ],
    };
}
