import { defineConfig } from "fumadocs-mdx/config";
import { rehypeCodeDefaultOptions, remarkAdmonition } from "fumadocs-core/mdx-plugins";
import { transformerDefaultTitle, transformerShellPrompt } from "./src/lib/shiki-transformers";

// Collections are generated by scripts/generate-sources.mjs (run before this
// file is ever read, via the "site:dev"/"site:build" pnpm scripts) — one repo
// dynamically discovered under content/, general/, dev-fixtures/, plus this
// repo's own docs/, becomes one literal `export const repo_x = defineDocs(...)`.
export * from "./content-sources.generated";

export default defineConfig({
    mdxOptions: {
        // Docusaurus-style `:::tip ... :::` admonitions, used throughout the
        // migrated content — renders as Fumadocs' <Callout> automatically.
        // Must append (not replace) fumadocs-mdx's own default remark plugins.
        remarkPlugins: (v) => [...v, remarkAdmonition],
        rehypeCodeOptions: {
            ...rehypeCodeDefaultOptions,
            lazy: false,
            langAlias: {
                // `env` isn't a real Shiki grammar — some repos fence .env-style
                // snippets as ```env; treat it as shell-like key=value highlighting.
                env: "bash",
            },
            transformers: [
                ...(rehypeCodeDefaultOptions.transformers ?? []),
                transformerDefaultTitle(),
                transformerShellPrompt(),
            ],
        },
    },
});
