// Discovers every TrickFire project with docs and wires them up as independent
// Fumadocs content sources.
//
// Runs as a plain Node step *before* `next dev` / `next build` (see package.json
// "site:dev" / "site:build"), because fumadocs-mdx needs literal top-level
// `export const x = defineDocs(...)` statements in source.config.ts - it can't
// take a dynamically-sized list of collections directly. So this script writes
// those literal exports to content-sources.generated.ts first.
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();

const FRAMEWORK_REPO = {
    id: "trickfire-docs",
    name: "Docs Framework",
    description: "Documentation for the TrickFire Docs framework itself",
    icon: "Blocks",
    contentDir: path.join(ROOT, "docs"),
    config: null,
};

function readDocsConfig(repoDir) {
    const configPath = path.join(repoDir, "docs.config.json");
    if (!fs.existsSync(configPath)) return null;
    try {
        return JSON.parse(fs.readFileSync(configPath, "utf-8"));
    } catch (err) {
        console.warn(`[generate-sources] failed to parse ${configPath}: ${err.message}`);
        return null;
    }
}

function isDir(p) {
    return fs.existsSync(p) && fs.statSync(p).isDirectory();
}

function buildRepo(repoDir, id) {
    const config = readDocsConfig(repoDir);
    if (!config) return null;

    const docsSubdir = path.join(repoDir, "docs");
    const contentDir = isDir(docsSubdir) ? docsSubdir : repoDir;

    return {
        id,
        name: config.name ?? id,
        description: config.description ?? "",
        icon: config.icon ?? null,
        contentDir,
        config,
    };
}

function reposFromDir(baseDir) {
    if (!isDir(baseDir)) return [];
    return fs
        .readdirSync(baseDir, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name)
        .sort()
        .map((id) => buildRepo(path.join(baseDir, id), id))
        .filter((r) => r !== null);
}

const generalDir = path.join(ROOT, "general");
const generalRepo = isDir(generalDir) ? buildRepo(generalDir, "general") : null;

const repos = [
    FRAMEWORK_REPO,
    ...(generalRepo ? [generalRepo] : []),
    ...reposFromDir(path.join(ROOT, "content")),
];

// --- content-sources.generated.ts + .map.json -------------------------------

const varName = (id) => `repo_${id.replace(/[^a-zA-Z0-9]/g, "_")}`;

const collectionLines = [
    `// @generated by scripts/generate-sources.mjs - do not edit`,
    `import { defineDocs } from "fumadocs-mdx/config";`,
    `import { metaSchema, pageSchema } from "fumadocs-core/source/schema";`,
    ``,
    ...repos.map((repo) => {
        const dir = path.relative(ROOT, repo.contentDir).split(path.sep).join("/");
        return `export const ${varName(repo.id)} = defineDocs({ dir: ${JSON.stringify(dir)}, docs: { schema: pageSchema }, meta: { schema: metaSchema } });`;
    }),
    ``,
];

fs.writeFileSync(path.join(ROOT, "content-sources.generated.ts"), collectionLines.join("\n"));

const map = Object.fromEntries(repos.map((repo) => [varName(repo.id), repo.id]));
fs.writeFileSync(path.join(ROOT, "content-sources.map.json"), JSON.stringify(map, null, 2) + "\n");

// --- repos.generated.json (metadata for navbar / switcher / homepage) -------

fs.writeFileSync(
    path.join(ROOT, "repos.generated.json"),
    JSON.stringify(
        repos.map(({ id, name, description, icon }) => ({ id, name, description, icon })),
        null,
        2
    ) + "\n"
);

// --- meta.json per repo, generated from docs.config.json's `sidebar` --------
//
// Real-world sidebar configs are flat: top-level doc items, plus at most one
// level of groups whose items live in a matching subfolder (e.g. "Guides" ->
// guides/*.md). That maps directly onto Fumadocs' folder + meta.json
// convention. Deeper nesting or groups whose items don't share a folder are a
// known Phase 1 limitation - noted in the redesign plan.

function basenameOfSlug(slug) {
    return slug.split("/").pop();
}

function firstSlug(items) {
    for (const item of items) {
        if ("items" in item) {
            const found = firstSlug(item.items);
            if (found) return found;
        } else if (item.slug) {
            return item.slug;
        }
    }
    return null;
}

function writeMeta(dir, meta) {
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, "meta.json"), JSON.stringify(meta, null, 2) + "\n");
}

function generateMetaFiles(repo) {
    const sidebar = repo.config?.sidebar;
    if (!sidebar || !isDir(repo.contentDir)) return;

    const rootPages = [];

    for (const item of sidebar) {
        if ("items" in item) {
            const sampleSlug = firstSlug(item.items);
            if (!sampleSlug) continue; // group has no local doc to anchor a folder to
            const folderName = sampleSlug.split("/")[0];
            rootPages.push(folderName);

            const groupPages = item.items
                .filter((sub) => "slug" in sub && sub.slug)
                .map((sub) => basenameOfSlug(sub.slug));

            writeMeta(path.join(repo.contentDir, folderName), {
                title: item.label,
                ...(item.icon && { icon: item.icon }),
                pages: groupPages,
                // Categories render flat and expanded, not as click-to-open accordions.
                defaultOpen: true,
                collapsible: false,
            });
        } else if (item.slug) {
            rootPages.push(basenameOfSlug(item.slug));
        }
    }

    writeMeta(repo.contentDir, {
        title: repo.name,
        ...(repo.icon && { icon: repo.icon }),
        pages: rootPages,
    });
}

for (const repo of repos) {
    generateMetaFiles(repo);
}

// The framework's own docs/ has no docs.config.json to read a sidebar order
// from, so its page ordering is defined by hand here instead.
writeMeta(FRAMEWORK_REPO.contentDir, {
    title: FRAMEWORK_REPO.name,
    icon: FRAMEWORK_REPO.icon,
    pages: [
        "index",
        "architecture",
        "member-guide",
        "writing-content",
        "sidebar-config",
        "configuration",
        "deployment",
    ],
});
writeMeta(path.join(FRAMEWORK_REPO.contentDir, "deployment"), {
    title: "Deployment",
    pages: ["index", "server-setup", "cloudflare-tunnel"],
    defaultOpen: true,
    collapsible: false,
});

console.log(
    `[generate-sources] wired ${repos.length} project(s): ${repos.map((r) => r.id).join(", ")}`
);
