// Discovers every TrickFire project with docs and wires them up as independent
// Fumadocs content sources.
//
// Runs as a plain step *before* `next dev` / `next build` (see package.json
// "site:dev" / "site:build"), because fumadocs-mdx needs literal top-level
// `export const x = defineCollections(...)` statements in source.config.ts -
// it can't take a dynamically-sized list of collections directly. So this
// script writes those literal exports to content-sources.generated.ts first.
import fs from "node:fs";
import path from "node:path";
import type { DocsConfig, SidebarItem } from "../framework/config/schema.js";

const ROOT = process.cwd();

interface Repo {
    id: string;
    name: string;
    description: string;
    icon: string | null;
    contentDir: string;
    config: DocsConfig;
}

function readDocsConfig(repoDir: string): DocsConfig | null {
    const configPath = path.join(repoDir, "docs.config.json");
    if (!fs.existsSync(configPath)) return null;
    try {
        return JSON.parse(fs.readFileSync(configPath, "utf-8")) as DocsConfig;
    } catch (err) {
        console.warn(`[generate-sources] failed to parse ${configPath}: ${(err as Error).message}`);
        return null;
    }
}

function isDir(p: string): boolean {
    return fs.existsSync(p) && fs.statSync(p).isDirectory();
}

function buildRepo(repoDir: string, id: string): Repo | null {
    const config = readDocsConfig(repoDir);
    if (!config) return null;

    const docsSubdir = path.join(repoDir, "docs");
    const contentDir = isDir(docsSubdir) ? docsSubdir : repoDir;

    return {
        id,
        name: config.name ?? id,
        description: config.description ?? "",
        icon: config.icon ?? null,
        contentDir,
        config,
    };
}

function reposFromDir(baseDir: string): Repo[] {
    if (!isDir(baseDir)) return [];
    return fs
        .readdirSync(baseDir, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name)
        .sort()
        .map((id) => buildRepo(path.join(baseDir, id), id))
        .filter((r): r is Repo => r !== null);
}

// This repo's own docs follow the exact same docs.config.json + docs/
// convention as every member repo - see docs.config.json at the repo root.
const frameworkRepo = buildRepo(ROOT, "trickfire-docs");
if (!frameworkRepo) {
    throw new Error("[generate-sources] missing or invalid docs.config.json at repo root");
}

const generalDir = path.join(ROOT, "general");
const generalRepo = isDir(generalDir) ? buildRepo(generalDir, "general") : null;

const repos: Repo[] = [
    frameworkRepo,
    ...(generalRepo ? [generalRepo] : []),
    ...reposFromDir(path.join(ROOT, "content")),
];

// --- content-sources.generated.ts + .map.json -------------------------------
//
// Docs and meta.json live in separate directory trees - meta.json is
// generated output and shouldn't clutter a synced repo's content/ mirror (or
// this repo's own docs/). fumadocs-mdx's `defineDocs()` convenience wrapper
// only supports a single shared `dir` for both, so each repo gets two
// `defineCollections()` entries instead (`<var>_docs`, `<var>_meta`) with
// independent dirs, combined manually via `toFumadocsSource()` in
// src/lib/source.ts. Fumadocs matches them up by relative path, so
// `.meta/<repo>/guides/meta.json` pairs with `content/<repo>/guides/*.md` as
// long as the subfolder structure mirrors.

const varName = (id: string) => `repo_${id.replace(/[^a-zA-Z0-9]/g, "_")}`;
const metaDirFor = (repo: Repo) => path.join(ROOT, ".meta", repo.id);

const collectionLines = [
    `// @generated by scripts/generate-sources.ts - do not edit`,
    `import { defineCollections } from "fumadocs-mdx/config";`,
    `import { metaSchema, pageSchema } from "fumadocs-core/source/schema";`,
    ``,
    ...repos.flatMap((repo) => {
        const docsDir = path.relative(ROOT, repo.contentDir).split(path.sep).join("/");
        const metaDir = path.relative(ROOT, metaDirFor(repo)).split(path.sep).join("/");
        const v = varName(repo.id);
        return [
            `export const ${v}_docs = defineCollections({ type: "doc", dir: ${JSON.stringify(docsDir)}, files: ["**/*.{md,mdx}", "!assets/**"], schema: pageSchema });`,
            `export const ${v}_meta = defineCollections({ type: "meta", dir: ${JSON.stringify(metaDir)}, schema: metaSchema });`,
        ];
    }),
    ``,
];

fs.writeFileSync(path.join(ROOT, "content-sources.generated.ts"), collectionLines.join("\n"));

const map = Object.fromEntries(repos.map((repo) => [varName(repo.id), repo.id]));
fs.writeFileSync(path.join(ROOT, "content-sources.map.json"), JSON.stringify(map, null, 2) + "\n");

// --- repos.generated.json (metadata for navbar / switcher / homepage) -------

fs.writeFileSync(
    path.join(ROOT, "repos.generated.json"),
    JSON.stringify(
        repos.map(({ id, name, description, icon }) => ({ id, name, description, icon })),
        null,
        2
    ) + "\n"
);

// --- meta.json per repo, generated from docs.config.json's `sidebar` --------
//
// Real-world sidebar configs are flat: top-level doc items, plus at most one
// level of groups whose items live in a matching subfolder (e.g. "Guides" ->
// guides/*.md). That maps directly onto Fumadocs' folder + meta.json
// convention. Deeper nesting or groups whose items don't share a folder are a
// known Phase 1 limitation - noted in the redesign plan.

function basenameOfSlug(slug: string): string {
    return slug.split("/").pop()!;
}

function firstSlug(items: SidebarItem[]): string | null {
    for (const item of items) {
        if ("items" in item) {
            const found = firstSlug(item.items);
            if (found) return found;
        } else if (item.slug) {
            return item.slug;
        }
    }
    return null;
}

function writeMeta(dir: string, meta: Record<string, unknown>): void {
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, "meta.json"), JSON.stringify(meta, null, 2) + "\n");
}

function generateMetaFiles(repo: Repo): void {
    const sidebar = repo.config.sidebar;
    if (!sidebar || !isDir(repo.contentDir)) return;

    const metaDir = metaDirFor(repo);
    const rootPages: string[] = [];

    for (const item of sidebar) {
        if ("items" in item) {
            const sampleSlug = firstSlug(item.items);
            if (!sampleSlug) continue; // group has no local doc to anchor a folder to
            const folderName = sampleSlug.split("/")[0];
            rootPages.push(folderName);

            const groupPages = item.items
                .filter(
                    (sub): sub is Extract<SidebarItem, { slug?: string }> =>
                        "slug" in sub && !!sub.slug
                )
                .map((sub) => basenameOfSlug(sub.slug!));

            writeMeta(path.join(metaDir, folderName), {
                title: item.label,
                ...(item.icon && { icon: item.icon }),
                pages: groupPages,
                // Categories render flat and expanded, not as click-to-open accordions.
                defaultOpen: true,
                collapsible: false,
            });
        } else if (item.slug) {
            rootPages.push(basenameOfSlug(item.slug));
        }
    }

    writeMeta(metaDir, {
        title: repo.name,
        ...(repo.icon && { icon: repo.icon }),
        pages: rootPages,
    });
}

for (const repo of repos) {
    generateMetaFiles(repo);
}

console.log(
    `[generate-sources] wired ${repos.length} project(s): ${repos.map((r) => r.id).join(", ")}`
);
