---
title: Sidebar Configuration
---

By default, pages are sorted alphabetically by filename, with folder and file names title-cased for their sidebar labels. This works for most projects.

If you need precise control over ordering, labels, or icons, define the sidebar explicitly in `docs.config.json`.

## Explicit sidebar

```json
{
    "$schema": "https://docs.trickfirerobotics.com/docs.config.schema.json",
    "name": "My Project",
    "description": "...",
    "sidebar": [
        { "label": "Getting Started", "slug": "getting-started" },
        {
            "label": "Guides",
            "items": [
                { "label": "Installation", "slug": "guides/installation" },
                { "label": "Configuration", "slug": "guides/configuration" }
            ]
        },
        {
            "label": "Reference",
            "items": [
                { "label": "API", "slug": "reference/api" },
                { "label": "FAQ", "slug": "reference/faq" }
            ]
        },
        { "label": "TrickFire GitHub", "link": "https://github.com/TrickfireRobotics" }
    ]
}
```

Setting `sidebar` generates a `meta.json` file next to your docs (and inside each group's subfolder) that pins the page order, group label, and icon. You don't write `meta.json` by hand - it's regenerated from `docs.config.json` on every `trickfire-docs dev` / `trickfire-docs build`.

## Item types

### Doc link

Links to a page in your `docs/` folder. Use `slug` - the path relative to `docs/` without the `.md` extension.

```json
{ "label": "Getting Started", "slug": "getting-started" }
{ "label": "API Reference",   "slug": "reference/api" }
```

### External link

Links to any URL. Use `link` instead of `slug`.

```json
{ "label": "GitHub", "link": "https://github.com/TrickfireRobotics" }
{ "label": "Notion", "link": "https://notion.so/trickfire" }
```

### Group (category)

Nests items under a heading, rendered as a flat, always-expanded section (no accordion). A group's items must live in a matching subfolder - e.g. the `"Guides"` group above expects its docs under `docs/guides/`.

```json
{
    "label": "Guides",
    "icon": "Rocket",
    "items": [
        { "label": "Page A", "slug": "guides/page-a" },
        { "label": "Page B", "slug": "guides/page-b" }
    ]
}
```

`icon` is optional - a [lucide-react](https://lucide.dev/icons/) icon name shown next to the group label.

## Autogenerated sidebar (default)

When `sidebar` is not set in `docs.config.json`, pages are listed alphabetically by filename with no grouping. Use an explicit sidebar when you need custom ordering, labels, icons, grouped categories, or external links.
