name: Deploy Docs

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy:
        name: Rebuild and deploy to server
        runs-on: [self-hosted, docs]
        permissions:
            contents: read
            deployments: write
        environment:
            name: production
            url: https://docs.trickfirerobotics.com

        steps:
            - name: Rebuild and deploy docs site
              run: bash /home/trickfire/docs/scripts/build.sh
